services:
  postgres:
    image: postgres:16-alpine
    container_name: chem-drill-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: chem_drill
      POSTGRES_PASSWORD: chem_drill_password
      POSTGRES_DB: chem_drill
    volumes:
      - pgdata:/var/lib/postgresql/data
  mailpit:
    image: axllent/mailpit
    container_name: chem-drill-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
  localstack:
    image: localstack/localstack
    container_name: chem-drill-localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3
    volumes:
      - ./localstack/init:/etc/localstack/init/ready.d
volumes:
  pgdata:
