/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
 
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "BasicAuthPassword": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BasicAuthUser": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BetterAuthSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DatabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GeminiApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SesFromEmail": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Web": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}